name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Install Dependencies
        run: pod install
      - name: Disable Library Validation
        run: /usr/libexec/PlistBuddy -c "Add :com.apple.security.cs.disable-library-validation bool true" ./Eigen/Eigen.entitlements
      - name: Set Build Version
        run: /usr/libexec/PlistBuddy -c "Set CFBundleVersion ${GITHUB_SHA::7}" ./Eigen/Info.plist 
      - name: Build
        run: xcodebuild -scheme Eigen -workspace Eigen.xcworkspace clean install CONFIGURATION_BUILD_DIR=build/root CODE_SIGN_IDENTITY=- | xcpretty && exit ${PIPESTATUS[0]}
      - name: Compress Artifact
        run: tar -chzf build/root/Eigen.tar.gz -C build/root Eigen.app
      - name: Upload Application
        uses: actions/upload-artifact@v3
        with:
          name: Eigen.app
          path: build/root/Eigen.tar.gz
      - name: Upload Debug Symbols
        uses: actions/upload-artifact@v3
        with:
          name: Eigen.app.dSYM
          path: build/root/Eigen.app.dSYM
